### ISSUE TITLE
数据库设计

### ISSUE THREAD

**Issue by Wooding-wood** [LouPlus/jobplus1#20]
# 数据库设计 #7 
### 基类Base
created_at: 创建时间 | 默认为utcnow()
updated_at: 更新时间 | 更新数据库后默认为utcnow()

#### ID | 用户级别 | 用户名 | 邮箱 | 密码 | logo | 公司id（外） | 求职id（外） | 创建时间 | 更新时间 
---
#### tablename='user'
id：ID主键
role：角色|uniq
name：用户名 | uniq | len(32)
email：邮箱 | uniq | len(64)
password: 密码 | uniq | len(256) | 使用setter写装饰器实现 并存储其hash
logo： 头像 | 如何存储该资源
company_id: 公司外键 | 当role为公司时，值不为null ？
employed_id: 求职者外键 | 当role为求职者是，值不为null ？
created_at: 基类
updated_at: 基类

#### ID | 性别 | 地址 | 描述 | 简历
---
#### tablename='employed'
id：ID | 主键
sex：性别 | uniq | 
location：地址 | len(64)
detail：描述 | len(256)
resume: 简历 | 是存上传的文件URI还是直接将文件存数据库

#### ID | 网址 | 地址 | 一句话描述 | 详细描述
---
#### tablename='company'
id：ID | 主键
website：网址 | len(64)
location：地址 | len(64)
oneword：描述 | len(64)
detail: 描述 | len(64)

#### ID | 职位名 | 薪资 | 地址 | 公司id（外）| 描述 | 经验要求
---
#### tablename='job'
id：ID | 主键
name：职位名 | len(64) | uniqu
wage：薪资 | len(64)
location：地址 | len(64)
company_id：发布公司外键 | len(64) | uniqu
detail: 描述 | len(64)
experiment： 职位要求 | len(64)
                    ： 发布时间（继承Base基类，使用updated_at)

#### ID | 公司id（外） | 职位id（外）| 求职者id（外）| 简历（外）| 递送时间 | 查阅状态
---
#### tablename='send'
id : ID | 主键
company_id : 公司ID（外键） | uniq （是否可不需要该id，因为从job_id里可以读出，或者是显示公司名）
job_id : 职位ID （外键） | uniq
employed_id： 求职者ID（外键） | uniq
resume： 简历（外键）| uniq （是否也可以不需要，同样可从employed_id中读出
delivery_time : 递送时间 | 是否可以不需要（从Base基类created_at中读出）
qualify： 查阅状态 | default：未查阅

**Comment by wmn7** [comment]
# 一些建议

## 用户表
Employee是雇工的意思，用这个单词感觉会更加合适
logo： 头像 存储图片的url

## 企业表
把名字写全吧，company

## 求职表
求职者表Employed那里resume: 简历 那里可以存url
描述可以使用单词`description`

## 职位表
职位要求使用名字`Requirement`比较好，experiment是实验的意思

## 投递表
company_id和resume确实不是必须的，可以从job和empolyed中读取
递送时间是需要的，因为创建用户后不会马上投递，如果使用created_time则所有投递时间是一样的。

**Comment by EdwinYang2000** [comment]
其他同意， 就是created_time 继承基类 的 就应该 是创造这条数据的时间（投递时间）

**Comment by Wooding-wood** [comment]
# 数据库设计 #7 修改版（17.12.15） 

### 基类Base
created_at: 创建时间 | 默认为utcnow()
updated_at: 更新时间 | 更新数据库后默认为utcnow()

## 用户表User

#### ===>  _id_ | _role_ | _name_ | _email_ | _password_ | _logo_img_ | _company_id_ | _employee_id_ | _created_at_ | _updated_at_ 
#### ID | 用户级别 | 用户名 | 邮箱 | 密码 | logo | 公司id（外） | 求职id（外） | 创建时间 | 更新时间 
---
#### tablename='user'
id：ID主键
role：角色|uniq
name：用户名 | uniq | len(32)
email：邮箱 | uniq | len(64)
password: 密码 | uniq | len(256) | 使用setter写装饰器实现 并存储其hash
logo： 头像 | 存储该资源的url
company_id: 公司外键 | 当role为公司时，值不为null ？
===> employee_id: 求职者外键 | 当role为求职者是，值不为null ？
created_at: 基类
updated_at: 基类

## ===> 求职者表Employee
#### ===> _id_ | _sex_ | _location_ | _description_ | _resume_ 
#### ID | 性别 | 地址 | 描述 | 简历
---
#### tablename='employed'
id：ID | 主键
sex：性别 | uniq | 
location：地址 | len(64)
===> description：描述 | len(256)
resume: 简历 | 存储上传文件的URI

## ===> 企业表Company
#### ===> _id_ | _website_ | _location_ | _oneword_ | _description_
#### ID | 网址 | 地址 | 一句话描述 | 详细描述
---
#### tablename='company'
id：ID | 主键
website：网址 | len(64)
location：地址 | len(64)
oneword：描述 | len(64)
===> description: 描述 | len(64)

## 职位表Job
#### ===> _id_ | _name_ | _wage_ | _location_ | _company_id_ | _description_ | _requirement_
#### ID | 职位名 | 薪资 | 地址 | 公司id（外）| 描述 | 经验要求
---
#### tablename='job'
id：ID | 主键
name：职位名 | len(64) | uniqu
wage：薪资 | len(64)
location：地址 | len(64)
company_id：发布公司外键 | len(64) | uniqu
===> description: 描述 | len(64)
===> requirement： 职位要求 | len(64)
                    ： 发布时间（继承Base基类，使用updated_at)

## 投递表Send
#### ===> _id_ | _company_id_ | _job_id_ | _employee_id_ | _resume_ | _qualify_
#### ===> ID | 公司id（外） | 职位id（外）| 求职者id（外）| 简历（外） | 查阅状态
---
#### tablename='send'
id : ID | 主键
company_id : 公司ID（外键） | uniq （是否可不需要该id，因为从job_id里可以读出，或者是显示公司名）
job_id : 职位ID （外键） | uniq
===> employee_id： 求职者ID（外键） | uniq
resume： 简历（外键）| uniq （是否也可以不需要，同样可从employed_id中读出）
qualify： 查阅状态 | default：未查阅
            : 递送时间 | 从Base基类created_at中读出）
